class NarrativeAgent:
    """
    Phase 4: Explainable Insights Module
    Attaches reasoning and evidence lineage to all conclusions generated by the system.
    """
    def __init__(self, api_key=None):
        self.api_key = api_key
        
    def generate_explanation(self, analysis_dict: dict, anomaly_dict: dict, forecast_dict: dict) -> dict:
        """
        Creates a structured JSON explanation tracing every metric, anomaly, and forecast 
        back to its source logic and algorithm used.
        """
        explanations = []
        
        # Explain KPIs
        for kpi, val in analysis_dict.get('kpis', {}).items():
            explanations.append({
                "insight": f"{kpi}: {val}",
                "lineage": "Standard pandas math aggregation over numeric features",
                "confidence": "High (Deterministic Computation)"
            })
            
        # Explain Anomalies
        for flag in anomaly_dict.get('flags', []):
            explanations.append({
                "insight": f"Anomaly on row {flag.get('row_id')}: {flag.get('reason')}",
                "lineage": f"Detected via {flag.get('type')} isolated against column '{flag.get('column')}'",
                "confidence": "Medium (Statistical/ML Inference)"
            })
            
        # Explain Forecast
        if not forecast_dict.get('error'):
            model_used = forecast_dict.get('model', 'Unknown Model')
            target = forecast_dict.get('target', 'Target Vector')
            explanations.append({
                "insight": f"Generated forecast for {target} over the next intervals.",
                "lineage": f"Derived using {model_used} across historical trend vectors mapped to {forecast_dict.get('time_col')}.",
                "confidence": "Medium-Low (Predictive Modeling Uncertainty)"
            })
            
        return {
            "summary_narrative": "Explainability tracing completed. All outputs connected to base data truth.",
            "evidence_traces": explanations
        }
