from docx import Document
from io import BytesIO

class ReportAgent:
    """
    Phase 4: DOCX Output Generation
    Writes methodology, key findings, and action plans to DOCX.
    """
    def __init__(self):
        pass
        
    def execute(self, analysis_results: dict) -> BytesIO:
        doc = Document()
        doc.add_heading('Automated Intelligence Report', 0)
        
        doc.add_heading('1. Executive Summary', level=1)
        doc.add_paragraph("This report was auto-generated by the Output Engine based on the insights discovered by the Analysis Agent.")
        
        doc.add_heading('2. Key Performance Indicators (KPIs)', level=1)
        for k, v in analysis_results.get("kpis", {}).items():
            doc.add_paragraph(f"{k}: {v}", style='List Bullet')
            
        doc.add_heading('3. Automated Narrative & Insights', level=1)
        clean_text = analysis_results.get("narrative", "").replace('### ', '').replace('**', '')
        doc.add_paragraph(clean_text)
        
        # We skip inserting the images directly into DOCX for now 
        # as the PPTX Agent handles visual presentations better, 
        # but the infrastructure is here if needed.
        
        output = BytesIO()
        doc.save(output)
        output.seek(0)
        return output
